### ISSUE TITLE
log4j error "could not parse url"

### ISSUE THREAD

**Issue by stevemadere** [pmoust/s3s3mirror-docker#2]
Whenever I try to run the container, I get the following error:

log4j:ERROR Could not parse url [file:target/conf/log4j.xml].
java.io.FileNotFoundException: target/conf/log4j.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:140)
    at java.io.FileInputStream.<init>(FileInputStream.java:96)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:87)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:178)
..... (intermediate stack frames omitted)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:265)
    at org.cobbzilla.s3s3mirror.MirrorMain.<clinit>(MirrorMain.java)

log4j:WARN No appenders could be found for logger (com.amazonaws.internal.config.InternalConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

This is how I tried to run the container:

docker run \
  -e "AWS_ACCESS_KEY_ID=$AWS_IAM_ACCESS_KEY_ID" \
  -e "AWS_SECRET_ACCESS_KEY=$AWS_IAM_SECRET_KEY" \
  pmoust/s3s3mirror \
  "$SOURCE_BUCKET" \
  "$DEST_BUCKET"

**Comment by cobbzilla** [comment]
I do not maintain the s3s3mirror-docker image. You might file an issue with them.

**Comment by joshhiggins22** [comment]
@stevemadere  Try over writing the working directory at runtime, with `w="/opt/s3s3mirror"` like: 
`docker run -e AWS_ACCESS_KEY_ID=foo -e AWS_SECRET_ACCESS_KEY=bar -w="/opt/s3s3mirror" pmoust/s3s3mirror  s3://source s3://destination`

**Comment by pmoust** [comment]
@stevemadere @joshhiggins22 fixed in #3
